default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_super_user
  password: password
  host: 127.0.0.1

development:
  <<: *default
  database: netstock_development

test:
  <<: *default
  database: netstock_test

production:
  <<: *default
  database: netstock_production
  username: netstock
  password: <%= ENV['NETSTOCK_DATABASE_PASSWORD'] %>
